<div class="modTitle">Polityka Prywatności dla strony http://goldencrop.sourceforge.net</div>
<p>Ta strona używa <em>cookies</em> do zapamiętywania języka użytkownika. Zastosowanie na stronie reklam Google Adsense, może spowodować użycie dodatkowych plików cookies. Aby uzyskać szczegóły zapoznaj się z Polityką Prywatności Google Adsens.</p>
<p>Jeśli potrzebujesz więcej informacji lub masz jakiekolwiek pytania odnośnie niniejszej Polityki Prywatności, skontaktuj się z nami pisząc maila na adres podany w dziale "Kontakt".</p> 

<p> Na stronie http://goldencrop.sourceforge.net/ przywiązujemy ogromną wagę do prywatności naszych użytkowników. Niniejsza Polityka Prywatności wskazuje jakie rodzaj informacji o użytkowniku jest odbierany, przechowywany i przetwarzany przez stronę http://goldencrop.sourceforge.net/. </p> 
<h1>Pliki logów</h1>
<p>Podobnie jak wiele innych stron WWW, http://goldencrop.sourceforge.net/ wykorzystuje pliki logów. Informacje zawarte w plikach logów zawierają między innymi adres IP, rodzaj przeglądarki, nazwę dostawcy Internetu (ISP), znacznik czasu i daty, stronę referującą oraz ilość kliknięć pomocną w analizie statystycznej trendów, administrowaniu stroną, zapamiętywaniu ścieżki zwiedzania strony i zbieraniu danych demograficznych. Adres IP oraz inne informacje nie są w żaden sposób łączone z jakimikolwiek innymi informacjami umożliwiającymi identyfikację personalną.</p> 
<h1>Pliki Cookies i Web Beacons</h1>
<p>http://goldencrop.sourceforge.net/ używa plików cookies do przechowywania informacji o preferencjach użytkownika, zapamiętywania wybranych przez użytkownika ustawień strony, zapamiętywania stron odwiedzonych przez użytkownika, dostosowywania zawartości strony na podstawie specyficznych danych takich jak typ przeglądarki oraz innych informacji wysyłanych przez przeglądarkę (to jest domyślne działanie przeglądarki, żadne poufne ani personalne dane nie są wysyłane, chyba że użytkownik skonfiguruje przeglądarkę aby tak właśnie było). </p> 
<h1>Pliki Cookie DoubleClick DART</h1>
<ul> 
	<li> Google, jako dostawca usług reklamowych, używa plików cookies do wyświetlania reklam na http://goldencrop.sourceforge.net/.</li>
	<li> Dzięki użyciu cookie DART, Google może dostosowywać reklamę w zależności od sposobu poruszania się po stronie http://goldencrop.sourceforge.net/ i innych stronach w Internecie.</li>
	<li> Użytkownik może w każdej chwili zrezygnować z użycia cookie DART, odwiedzając "the Google ad and content network privacy policy" (politykę prywatności Google) pod adresem (URL): http://www.google.com/privacy_ads.html</li>
</ul>
<p> Niektórzy nasi partnerzy mogą używać cookie lub web beacons na naszej stronie. Nasi partnerzy to: <b> Google Adsense </b></p>

<p> Zewnętrzne serwery ogłoszeń lub sieci ogłoszeń używają specjalnej technologii w stosunku do reklam oraz odnośników, które mogą pojawić się na stronie http://goldencrop.sourceforge.net/. Są one wysyłane bezpośrednio do przeglądarki. Automatycznie odbierają twój adres IP gdy to wyświetlenie następuje. Inne technologie (takie jak cookies, JavaScript lub Web Beacons) może również być użyte przez zewnętrzne sieci ogłoszeń aby mierzyć efektywność ich ogłoszeń lub personalizować zawartość prezentowaną użytkownikowi</p> 
<p> http://goldencrop.sourceforge.net/ nie ma dostępu ani żadnej kontroli nad plikami cookie oraz innymi technologiami używanymi przez zewnętrznych ogłoszeniodawców. </p> 
<p> Powinieneś zapoznać się z odpowiednimi Politykami Prywatności zewnętrznych ogłoszeniodawców aby uzyskać bardziej szczegółowe informacje na temat ich działań oraz sposobu w jaki można zrezygnować z danych praktyk. Polityka Prywatności http://goldencrop.sourceforge.net/ nie ma w takich przypadkach zastosowania. Nie mamy żadnej możliwości kontroli takich zachowań zewnętrznych ogłoszeniodawców lub stron internetowych. </p> 
<p> Jeśli chcesz wyłączyć obsługę plików cookies w Twojej przeglądarce, skorzystaj ze stosownej opcji w menu lub ustawieniach przeglądarki. Bardziej dokładny opis możliwości zarządzania plikami cookies znajduje się na stronie WWW konkretnej przeglądarki. </p>